#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v27
# autospec commit: 65cf152
#
Name     : R-urltools
Version  : 1.7.3.1
Release  : 45
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/urltools_1.7.3.1.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/urltools_1.7.3.1.tar.gz
Summary  : Vectorised Tools for URL Handling and Parsing
Group    : Development/Tools
License  : MIT
Requires: R-urltools-lib = %{version}-%{release}
Requires: R-Rcpp
Requires: R-triebeard
BuildRequires : R-Rcpp
BuildRequires : R-triebeard
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
parsing, parameter extraction and modification. All functions are
    designed to be both fast and entirely vectorised. It is intended to be
    useful for people dealing with web-related datasets, such as server-side
    logs, although may be useful for other situations involving large sets of
    URLs.

%package lib
Summary: lib components for the R-urltools package.
Group: Libraries

%description lib
lib components for the R-urltools package.


%prep
%setup -q -n urltools
pushd ..
cp -a urltools buildavx2
popd
pushd ..
cp -a urltools buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1749773158

%install
export SOURCE_DATE_EPOCH=1749773158
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/urltools/DESCRIPTION
/usr/lib64/R/library/urltools/INDEX
/usr/lib64/R/library/urltools/LICENSE
/usr/lib64/R/library/urltools/Meta/Rd.rds
/usr/lib64/R/library/urltools/Meta/data.rds
/usr/lib64/R/library/urltools/Meta/features.rds
/usr/lib64/R/library/urltools/Meta/hsearch.rds
/usr/lib64/R/library/urltools/Meta/links.rds
/usr/lib64/R/library/urltools/Meta/nsInfo.rds
/usr/lib64/R/library/urltools/Meta/package.rds
/usr/lib64/R/library/urltools/Meta/vignette.rds
/usr/lib64/R/library/urltools/NAMESPACE
/usr/lib64/R/library/urltools/NEWS
/usr/lib64/R/library/urltools/R/urltools
/usr/lib64/R/library/urltools/R/urltools.rdb
/usr/lib64/R/library/urltools/R/urltools.rdx
/usr/lib64/R/library/urltools/data/Rdata.rdb
/usr/lib64/R/library/urltools/data/Rdata.rds
/usr/lib64/R/library/urltools/data/Rdata.rdx
/usr/lib64/R/library/urltools/doc/index.html
/usr/lib64/R/library/urltools/doc/urltools.R
/usr/lib64/R/library/urltools/doc/urltools.Rmd
/usr/lib64/R/library/urltools/doc/urltools.html
/usr/lib64/R/library/urltools/help/AnIndex
/usr/lib64/R/library/urltools/help/aliases.rds
/usr/lib64/R/library/urltools/help/paths.rds
/usr/lib64/R/library/urltools/help/urltools.rdb
/usr/lib64/R/library/urltools/help/urltools.rdx
/usr/lib64/R/library/urltools/html/00Index.html
/usr/lib64/R/library/urltools/html/R.css
/usr/lib64/R/library/urltools/tests/testthat.R
/usr/lib64/R/library/urltools/tests/testthat/test_credentials.R
/usr/lib64/R/library/urltools/tests/testthat/test_encoding.R
/usr/lib64/R/library/urltools/tests/testthat/test_get_set.R
/usr/lib64/R/library/urltools/tests/testthat/test_memory.R
/usr/lib64/R/library/urltools/tests/testthat/test_parameters.R
/usr/lib64/R/library/urltools/tests/testthat/test_parsing.R
/usr/lib64/R/library/urltools/tests/testthat/test_puny.R
/usr/lib64/R/library/urltools/tests/testthat/test_suffixes.R

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/urltools/libs/urltools.so
/V4/usr/lib64/R/library/urltools/libs/urltools.so
/usr/lib64/R/library/urltools/libs/urltools.so
